stages:
  generate:
    matrix:
      dataset: [train, dev, test]
    cmd: >-
      python ai_papers/generate.py
      data/raw/${item.dataset}.jsonl
      prompts/${prompt}.txt
      models/${model}
      preds/${item.dataset}.jsonl
    deps:
      - data/raw/${item.dataset}.jsonl
      - models/${model}
      - prompts/${prompt}.txt
      - ai_papers/generate.py
    params:
      - model
      - prompt
    outs:
      - preds/${item.dataset}.jsonl

  evaluate:
    matrix:
      dataset: [train, dev]
    cmd: >-
      python ai_papers/evaluate.py
      --params-file=params.yaml
      data/raw/${item.dataset}.jsonl
      preds/${item.dataset}.jsonl
      metrics/${item.dataset}.yaml
    deps:
      - data/raw/${item.dataset}.jsonl
      - preds/${item.dataset}.jsonl
      - ai_papers/evaluate.py
    params:
      - evaluate
    metrics:
      - metrics/${item.dataset}.yaml:
          cache: False
