answers:
  positive: "Yes"
  negative: "No"

make_examples:
  num_examples: 4
  random_seed: 42

generate:
  instruction: >-
    Use the title and abstract of the following academic paper to decide
    if it is about artificial intelligence or not. Output "Yes" if it is
    about AI, and "No" it it is not.
  model: gpt2
  prompt: baseline
  stop_token: '\n'
evaluate:
  precision: 5
